/**
 * payload-types.ts — Auto-generated by `pnpm generate-types`
 * -----------------------------------------------------------
 * This file is a STUB for the initial project setup.
 * Run `pnpm generate-types` once the database is connected to
 * replace this with the real auto-generated types.
 *
 * Do NOT edit manually — it will be overwritten by generate-types.
 */

/* eslint-disable */
// @ts-nocheck

export interface Config {
  collections: {
    products: Product;
    categories: Category;
    orders: Order;
    cities: City;
    'blog-posts': BlogPost;
    pages: Page;
    media: Media;
    users: User;
    influencers: Influencer;
    'logistics-partners': LogisticsPartner;
    reviews: Review;
  };
  globals: Record<string, never>;
}

export interface Product {
  id: string;
  slug: string;
  name_fr: string;
  name_ar?: string;
  category?: Category | string;
  price_mad: number;
  description_fr?: unknown; // RichText
  description_ar?: unknown; // RichText
  images?: Array<{ image: Media | string; id?: string }>;
  badges?: ('bestseller' | 'nouveau' | 'edition-limitee' | 'pack')[];
  material?: string;
  isLimited?: boolean;
  inStock?: boolean;
  sku?: string;
  seo?: { title?: string; description?: string; ogImage?: Media | string };
  createdAt: string;
  updatedAt: string;
}

export interface Category {
  id: string;
  slug: string;
  name_fr: string;
  name_ar?: string;
  description_fr?: string;
  description_ar?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Order {
  id: string;
  orderId: string;
  date?: string;
  prenom: string;
  nom: string;
  telephone: string;
  ville?: City | string;
  adresse: string;
  produit?: string;
  prix_mad?: number;
  note?: string;
  statut?: 'pending' | 'confirmed' | 'shipping' | 'delivered' | 'refused';
  livreur?: string;
  paye?: boolean;
  source?: 'website' | 'whatsapp' | 'upconfirm';
  metaFbc?: string;
  metaFbp?: string;
  createdAt: string;
  updatedAt: string;
}

export interface City {
  id: string;
  slug: string;
  name_fr: string;
  name_ar?: string;
  active?: boolean;
  region?: string;
  createdAt: string;
  updatedAt: string;
}

export interface BlogPost {
  id: string;
  slug: string;
  title_fr: string;
  title_ar?: string;
  excerpt_fr: string;
  excerpt_ar?: string;
  content_fr?: unknown; // RichText
  content_ar?: unknown; // RichText
  featuredImage: Media | string;
  category: 'guide' | 'conseil' | 'tendance' | 'education';
  tags?: Array<{ text: string; id?: string }>;
  author?: string;
  publishedAt: string;
  relatedProducts?: (Product | string)[];
  seo?: { title?: string; description?: string; ogImage?: Media | string; keywords?: string };
  createdAt: string;
  updatedAt: string;
}

export interface Page {
  id: string;
  slug: string;
  title: string;
  content?: unknown; // RichText
  seo?: { title?: string; description?: string };
  createdAt: string;
  updatedAt: string;
}

export interface Media {
  id: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  alt?: string;
  createdAt: string;
  updatedAt: string;
}

export interface User {
  id: string;
  email: string;
  role?: 'admin' | 'editor';
  createdAt: string;
  updatedAt: string;
}

export interface Influencer {
  id: string;
  username: string;
  platform?: string;
  followers?: number;
  email?: string;
  telephone?: string;
  status?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface LogisticsPartner {
  id: string;
  name: string;
  slug?: string;
  zones?: string[];
  contact?: string;
  notes?: string;
  createdAt: string;
  updatedAt: string;
}

export interface Review {
  id: string;
  productId?: Product | string;
  name: string;
  city?: string;
  rating: number;
  comment: string;
  approved?: boolean;
  createdAt: string;
  updatedAt: string;
}
