/**
 * Payload admin — import map
 * ---------------------------
 * This file is automatically regenerated by:
 *   pnpm payload generate:importmap
 *
 * It maps any custom admin components (fields, views, cells…) to their
 * actual module paths so the admin can load them on the server.
 *
 * We don't use custom admin components yet, so the map is empty.
 * Leave this file committed so the `page.tsx` and `not-found.tsx` imports
 * resolve on first run, before `generate:importmap` has ever been executed.
 */

export const importMap = {};
